<?php
/**
 * $FILE_NAME
 * ==============================================
 * 版权所有 2001-2016 http://www.zhmax.com
 * ----------------------------------------------
 * 这不是一个自由软件，未经授权不许任何使用和传播。
 * ----------------------------------------------
 * @date: 16-7-27 上午9:43
 * @author: LocoRoco<tqsq2005@gmail.com>
 * @version:v2016
 * @since:Yii2
 * ----------------------------------------------
 * 程序文件简介：
 * ==============================================
 */

/**
 * $FILE_NAME
 * ==============================================
 * 版权所有 2001-2016 http://www.zhmax.com
 * ----------------------------------------------
 * 这不是一个自由软件，未经授权不许任何使用和传播。
 * ----------------------------------------------
 * @date: 16-7-27 上午9:28
 * @author: LocoRoco<tqsq2005@gmail.com>
 * @version:v2016
 * @since:Yii2
 * ----------------------------------------------
 * 程序文件简介：
 * ==============================================
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their tanslations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '',
    'Action' => '操作方式',
    'Args' => '',
    'Audit' => '日志审计',
    'Audit Error in Audit Entry #{entry_id}' => '',
    'Audit Module' => '日志审计模块',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => '',
    'Created' => '操作时间',
    'Data' => '',
    'Database Trails' => '',
    'Diff' => '修改内容',
    'Difference' => '',
    'Download' => '',
    'Download eml file' => '',
    'Duration' => '',
    'Email Messages' => '',
    'Emailed' => '',
    'Entries' => '日志列表',
    'Entry #{id}' => '日志 #{id}',
    'Entry ID' => '日志ID',
    'Error' => '运行错误',
    'Error #{id}' => '运行错误 #{id}',
    'Error Code' => '',
    'Errors' => '运行错误列表',
    'Extra' => '',
    'Extra Data' => '',
    'Field' => '信息段',
    'File' => '',
    'From' => '',
    'Guest' => '游客',
    'HTML' => '',
    'HTML Body' => '',
    'Hash' => '',
    'ID' => '主键ID',
    'IP' => '',
    'Javascript' => '脚本错误',
    'Javascript #{id}' => '脚本错误 #{id}',
    'Javascripts' => '脚本错误列表',
    'Line' => '',
    'Mail' => '邮件',
    'Mail #{id}' => '邮件 #{id}',
    'Mails' => '邮件列表',
    'Memory' => '',
    'Mesage' => '',
    'New Value' => '修改后',
    'No' => '',
    'Old Value' => '修改前',
    'Origin' => '',
    'Profiling' => '性能分析',
    'Reply' => '',
    'Request' => '请求',
    'Request Method' => '',
    'Stack Trace' => '',
    'Subject' => '',
    'Successful' => '',
    'Text' => '',
    'Text Body' => '',
    'To' => '',
    'Trace' => '',
    'Trail' => '操作记录',
    'Trail #{id}' => '',
    'Trails' => '操作列表',
    'Type' => '类型',
    'User' => '',
    'User ID' => '操作员',
    'Yes' => '',
    'view audit entry' => '查看日志详情',
    '{message}' => '',
];
