<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advanced' => '高级设置',
    'Basic' => '基本信息',
    'Copy' => '复制',
    'Create' => '新增',
    'Create module' => '新增模块',
    'Delete item' => '确定要删除该记录吗',
    'Edit' => '修改',
    'Icon' => '图标',
    'List' => '列表',
    'Modules' => '模块',
    'Move down' => '下移',
    'Move up' => '上移',
    'Name' => '名称',
    'No records found' => '暂无记录',
    'Restore default settings' => '重置初始设置',
    'Save' => '保存',
    'Status' => '状态',
    'Title' => '标题',
    'module doesn`t have any settings.' => '该模块未做任何设置',
    'Reset' => '重置',
    'Control Panel' => '控制面板',
    'Welcome' => '欢迎',
    'Welcome to control panel, choose which section you want to manage in left menu.' => '',
    'Incorrect username or password.' => '用户名或密码错误.',
    'You tried to login too often. Please wait 5 minutes.' => '',
    'Class does not exist' => '类不存在',
    'Open site' => '前往宣传网',
    'Live edit' => '',
    'Username' => '用户名',
    'Password' => '密码',
    'Remember me' => '',
    'Class' => '',
    'Order' => '',
    'Value' => '',
    'Sign in' => '',
    'Login' => '',
    'Logout' => '',
    'Link' => '',
    'Text' => '内容',
    'Date' => '时间',
    'Add subcategory' => '增加下级分类',
    'Parent category' => '上级分类',
    'Turn Off' => '禁用',
    'Turn On' => '启用',
    'Delete' => '删除',
    'Slug' => '链接标识(Slug)',
    'Image' => '',
    'File' => '',
    'Views' => '',
    'Description' => '',
    'Send' => '提 交',
    'Upload' => '上传',
    'Upload photos' => '上传图片',
    'Settings' => '配置',
    'Back' => '',
    'Go back' => '',
    'New' => '',
    'All' => '列表',
    'Yes' => '是',
    'No' => '否',
    'Add' => '增加',
    'Update' => '修改',
    'Anti-spam check' => '',

    'Not found' => '',
    'Create error. {0}' => '',
    'Update error. {0}' => '',
    'Slug can contain only 0-9, a-z, A-Z and "-" characters (max: 128).' => '链接标识(Slug)只能包含 0-9、a-z、A-Z 及 横杠(-)，长度不能超过128.',
    'Slug can contain only 0-9, a-z and "-" characters (max: 128).' => '链接标识(Slug)只能包含 0-9、a-z、A-Z 及 横杠(-)，长度不能超过128.',

    'Only for developer' => '',
    'Preferences' => '系统配置参数列表',
    'Create Preferences' => '新增配置参数',
    'Edit Preferences' => '修改配置参数',
    'Preferences created' => '配置参数已新增',

    'Preferences updated' => '配置参数已修改',
    'Preferences deleted' => '配置参数已删除',

    'Edit module' => '修改模块',
    'Module created' => '模块已新增',
    'Module updated' => '模块已更新',
    'Module deleted' => '模块已删除',
    'Module settings updated' => '模块配置已更新',
    'Module default settings was restored' => '模块成功加载默认配置',

    'Admins' => '',
    'Create admin' => '',
    'Edit admin' => '',
    'Admin created' => '',
    'Admin updated' => '',
    'Admin deleted' => '',

    'Photos' => '照片',
    'Photo count' => '照片数量',
    'Photo description saved' => '照片描述信息已保存',
    'Photo deleted' => '照片已删除',
    'Photo uploaded' => '照片已上传',
    'No photos uploaded yet' => '无上传照片',
    'Bad response' => '',
    'File is incorrect' => '文件不正确',
    'File upload error. Check uploads folder for write permissions' => '文件上传失败，请检查服务器相关权限',
    'Change image' => '',
    'Uploading. Please wait' => '上传中，请稍候..',

    'System' => '',
    'Current version' => '',
    'Flush cache' => '',
    'Clear assets' => '',
    'Cache flushed' => '',
    'Logs' => '',
    'Seo texts' => '',
    'Articles' => '文章列表',
    'Article' => '文章',

    'Categories' => '分类列表',
    'Create category' => '新增分类',
    'Edit category' => '修改分类',

    'Items' => '',
    'Short' => '概要',

    'Category created' => '分类已新增',
    'Category updated' => '分类已修改',
    'Category deleted' => '分类已删除',
    'Category image cleared' => '分类附属图片已删除',
    'Status successfully changed' => '状态已更新',

    'Create article' => '新增文章',
    'Edit article' => '修改文章',
    'Article created' => '文章已新增',
    'Article updated' => '文章已更新',
    'Article deleted' => '文章已删除',

    'Clear image' => '删除图片',
    'Image cleared' => '图片已删除',
];
