<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '',
    'A password will be generated automatically if not provided' => '如果不设置密码，系统将自动生成随机密码',
    'Account' => '账户',
    'Account details' => '基本信息',
    'Account settings' => '',
    'Already registered? Sign in!' => '',
    'Are you sure you want to block this user?' => '锁定该用户，确定吗？',
    'Are you sure you want to confirm this user?' => '审核通过该用户，确定吗？',
    'Are you sure you want to delete this user?' => '删除该用户，确定吗？',
    'Are you sure you want to unblock this user?' => '解锁该用户，确定吗？',
    'Assignments' => '',
    'Block' => '锁定',
    'Block status' => '账号状态',
    'Blocked at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Change your avatar at Gravatar.com' => '',
    'Confirm' => '待审核',
    'Confirmation' => '审核情况',
    'Confirmation status' => '',
    'Confirmed' => '已审核',
    'Confirmed at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Connect' => '',
    'Continue' => '',
    'Create' => '创建',
    'Create a user account' => '创建新用户',
    'Credentials will be sent to the user by email' => '注册确认信息将会发送到该用户邮箱',
    'Delete' => '',
    'Didn\'t receive confirmation message?' => '',
    'Disconnect' => '',
    'Don\'t have an account? Sign up!' => '',
    'Finish' => '',
    'Forgot password?' => '',
    'Hello' => '',
    'If you already registered, sign in and connect this account on settings page' => '',
    'If you cannot click the link, please try pasting the text into your browser' => '',
    'If you did not make this request you can ignore this email' => '',
    'In order to complete your registration, please click the link below' => '',
    'In order to complete your request, please click the link below' => '',
    'In order to finish your registration, we need you to enter following fields' => '',
    'Information' => '',
    'Joined on {0, date}' => '',
    'Manage users' => '用户管理',
    'Networks' => '',
    'New permission' => '',
    'New role' => '',
    'New user' => '新用户',
    'Not blocked' => '',
    'Password' => '密码',
    'Permissions' => '',
    'Please click the link below to complete your password reset' => '',
    'Profile' => '用户资料',
    'Profile details' => '',
    'Profile settings' => '',
    'Recover your password' => '',
    'Registration IP' => '注册IP',
    'Registration time' => '注册时间',
    'Request new confirmation message' => '',
    'Reset your password' => '重置密码',
    'Roles' => '',
    'Save' => '保存',
    'Sign in' => '登录',
    'Sign up' => '注册',
    'Thank you for signing up on {0}' => '',
    'Unblock' => '解锁',
    'Unconfirmed' => '',
    'Update' => '',
    'Update user account' => '',
    'Users' => '用户列表',
    'We have generated a password for you' => '',
    'We have received a request to change the email address for your account on {0}' => '',
    'We have received a request to reset the password for your account on {0}' => '',
    'You can assign multiple roles or permissions to user by using the form below' => '',
    'You can connect multiple accounts to be able to log in using them' => '',
    'Your account on {0} has been created' => '',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
    /* model User's labels */
    'Username' => '用户名',
    'Email' => '邮箱',
    'Registration ip' => '注册IP',
    'New email' => '新的邮箱',
    'Confirmation time' => '审核时间',

];
